### ISSUE TITLE
accessToken seems to be required 

### ISSUE THREAD

**Issue by verdavaine** [spencercarli/react-native-meteor-google-oauth#1]
Hi, 
Thank you for all explanations about using react-native with meteor !
Just followed blog.differential.com/meteor-google-oauth-from-react-native and tried it on android device.
I get on error on meteor server when 'signing in with Google' :
Exception while invoking method 'login' Error: Failed to fetch tokeninfo from Google. failed [400] {  "error": "invalid_token",  "error_description": "Invalid Value" }

I have read in the 'react-native-google-signin' documentation that the user returned by GoogleSignin.signIn() only contains an accessToken for iOS.
This could explain the exception from 'getScopes' function inside your meteor-accounts-google-oauth package.
(I dont have problem with the idtoken and get correct result with  https://www.googleapis.com/oauth2/v3/tokeninfo?id_token="id_token")

Have u succeeded to 'sign in with Google' on android simulator ?

**Comment by spencercarli** [comment]
Ah, okay I see my mistake. I'll try to get to this soon! Apologies for the confusion.

Do you know of any docs explaining how I could getScopes and other data without an accessToken?

Thanks for bringing this up!

**Comment by verdavaine** [comment]
Sorry I don't know doc about 'getScopes and other data without an
accessToken'
In fact I am not specialized in android development, I just tried
previously Cordova with meteor.

I have 2 questions about this code. These are not issues as it works. I am
just curious !

componentWillReceiveProps(nextProps) {
  if (nextProps) {
    GoogleSignin.currentUserAsync()
        .then((user) => {
          this.handleDDPSignIn(user)
          this.props.changedSignedIn(true);
        })
        .done();
  }
}

First :
Is there any reason for testing GoogleSignin.currentUserAsync() inside
componentWillReceiveProp(nextProps) and not inside componentDidMount as
recommended inside react-native-google-signin doc ?

Second :
Is it necessary to test GoogleSignin.currentUserAsync() ?
When reopening the app, if we previouly Google sign in, we have token
registered and will 'loginWith Token' as soon as ddpClient is connected.

Aren't token registration and GoogleSignin.currentUserAsync() test
redundant ?
Maybe we dont need to register token for Google SignIn (but still need to
do it for email SignIn)

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=paul75011@gmail.com&idSignature=22

2016-03-29 16:51 GMT+02:00 Spencer Carli notifications@github.com:

**Comment by spencercarli** [comment]
The reason that check sits in a `componentWillReceiveProp` is that the template will render before our server connection is established (to the Meteor server). So we want to rerun that whenever our connection status changes.

The reason this

``` javascript
GoogleSignin.currentUserAsync()
        .then((user) => {
          this.handleDDPSignIn(user)
          this.props.changedSignedIn(true);
        })
        .done();
```

exists is incase the login token expired on the Meteor server. We can make that round trip to Google, auth our user again, and sign them back into the Meteor server without the user having to input anything.

**Comment by spencercarli** [comment]
Referencing this doc: https://developers.google.com/identity/sign-in/android/offline-access#enable_server-side_api_access_for_your_app

I think what needs to happen is a server method needs to be called that can accept and auth token (which seems to be returned from Google) and exchange it for access and refresh tokens.

I'm not sure when I'll be able to jump on this (Android is very much outside of my normal dev cycle so it takes a decent time investment just to get up and running). I've at least got somewhere to look when I can :)

**Comment by spencercarli** [comment]
Closing because I think this is no longer an issue w/ latest versions of the react-native-google-sign-in package

**Comment by ujwal-setlur** [comment]
Actually, with react-native-google-signin 0.8.1 (the latest at this time), the accessToken is not returned on Android. 

https://github.com/devfd/react-native-google-signin/issues/147
